name: dart_lang_sample_library_1
description: A thing that can be imported from another dart-lang project
version: 1.0.0
homepage: https://github.com/easoncxz/dart-lang-sample-lib-1

environment:
  sdk: '>=2.16.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
